using GLFW;

namespace ZGF.KeyboardModule.GlfwAdapter;

public static class KeysExtensions
{
    public static KeyboardKey Adapt(this Keys key) => key switch
    {
        Keys.Unknown => KeyboardKey.Unknown,

        Keys.Space => KeyboardKey.Space,
        Keys.Apostrophe => KeyboardKey.Apostrophe,
        Keys.Comma => KeyboardKey.Comma,
        Keys.Minus => KeyboardKey.Minus,
        Keys.Period => KeyboardKey.Period,
        Keys.Slash => KeyboardKey.Slash,

        Keys.Alpha0 => KeyboardKey.Alpha0,
        Keys.Alpha1 => KeyboardKey.Alpha1,
        Keys.Alpha2 => KeyboardKey.Alpha2,
        Keys.Alpha3 => KeyboardKey.Alpha3,
        Keys.Alpha4 => KeyboardKey.Alpha4,
        Keys.Alpha5 => KeyboardKey.Alpha5,
        Keys.Alpha6 => KeyboardKey.Alpha6,
        Keys.Alpha7 => KeyboardKey.Alpha7,
        Keys.Alpha8 => KeyboardKey.Alpha8,
        Keys.Alpha9 => KeyboardKey.Alpha9,

        Keys.SemiColon => KeyboardKey.SemiColon,
        Keys.Equal => KeyboardKey.Equals,

        Keys.A => KeyboardKey.A,
        Keys.B => KeyboardKey.B,
        Keys.C => KeyboardKey.C,
        Keys.D => KeyboardKey.D,
        Keys.E => KeyboardKey.E,
        Keys.F => KeyboardKey.F,
        Keys.G => KeyboardKey.G,
        Keys.H => KeyboardKey.H,
        Keys.I => KeyboardKey.I,
        Keys.J => KeyboardKey.J,
        Keys.K => KeyboardKey.K,
        Keys.L => KeyboardKey.L,
        Keys.M => KeyboardKey.M,
        Keys.N => KeyboardKey.N,
        Keys.O => KeyboardKey.O,
        Keys.P => KeyboardKey.P,
        Keys.Q => KeyboardKey.Q,
        Keys.R => KeyboardKey.R,
        Keys.S => KeyboardKey.S,
        Keys.T => KeyboardKey.T,
        Keys.U => KeyboardKey.U,
        Keys.V => KeyboardKey.V,
        Keys.W => KeyboardKey.W,
        Keys.X => KeyboardKey.X,
        Keys.Y => KeyboardKey.Y,
        Keys.Z => KeyboardKey.Z,

        Keys.LeftBracket => KeyboardKey.LeftBracket,
        Keys.Backslash => KeyboardKey.Backslash,
        Keys.RightBracket => KeyboardKey.RightBracket,
        Keys.GraveAccent => KeyboardKey.GraveAccent,

        // World1/World2 are non-US keys with no portable mapping.
        Keys.World1 => KeyboardKey.Unknown,
        Keys.World2 => KeyboardKey.Unknown,

        Keys.Escape => KeyboardKey.Escape,
        Keys.Enter => KeyboardKey.Enter,
        Keys.Tab => KeyboardKey.Tab,
        Keys.Backspace => KeyboardKey.Backspace,
        Keys.Insert => KeyboardKey.Insert,
        Keys.Delete => KeyboardKey.Delete,

        Keys.Right => KeyboardKey.RightArrow,
        Keys.Left => KeyboardKey.LeftArrow,
        Keys.Down => KeyboardKey.DownArrow,
        Keys.Up => KeyboardKey.UpArrow,

        Keys.PageUp => KeyboardKey.PageUp,
        Keys.PageDown => KeyboardKey.PageDown,
        Keys.Home => KeyboardKey.Home,
        Keys.End => KeyboardKey.End,

        Keys.CapsLock => KeyboardKey.CapsLock,
        Keys.ScrollLock => KeyboardKey.ScrollLock,
        Keys.NumLock => KeyboardKey.NumLock,
        Keys.PrintScreen => KeyboardKey.PrintScreen,
        Keys.Pause => KeyboardKey.Pause,

        Keys.F1 => KeyboardKey.F1,
        Keys.F2 => KeyboardKey.F2,
        Keys.F3 => KeyboardKey.F3,
        Keys.F4 => KeyboardKey.F4,
        Keys.F5 => KeyboardKey.F5,
        Keys.F6 => KeyboardKey.F6,
        Keys.F7 => KeyboardKey.F7,
        Keys.F8 => KeyboardKey.F8,
        Keys.F9 => KeyboardKey.F9,
        Keys.F10 => KeyboardKey.F10,
        Keys.F11 => KeyboardKey.F11,
        Keys.F12 => KeyboardKey.F12,
        Keys.F13 => KeyboardKey.F13,
        Keys.F14 => KeyboardKey.F14,
        Keys.F15 => KeyboardKey.F15,
        Keys.F16 => KeyboardKey.F16,
        Keys.F17 => KeyboardKey.F17,
        Keys.F18 => KeyboardKey.F18,
        Keys.F19 => KeyboardKey.F19,
        Keys.F20 => KeyboardKey.F20,
        Keys.F21 => KeyboardKey.F21,
        Keys.F22 => KeyboardKey.F22,
        Keys.F23 => KeyboardKey.F23,
        Keys.F24 => KeyboardKey.F24,
        Keys.F25 => KeyboardKey.F25,

        Keys.Numpad0 => KeyboardKey.Numpad0,
        Keys.Numpad1 => KeyboardKey.Numpad1,
        Keys.Numpad2 => KeyboardKey.Numpad2,
        Keys.Numpad3 => KeyboardKey.Numpad3,
        Keys.Numpad4 => KeyboardKey.Numpad4,
        Keys.Numpad5 => KeyboardKey.Numpad5,
        Keys.Numpad6 => KeyboardKey.Numpad6,
        Keys.Numpad7 => KeyboardKey.Numpad7,
        Keys.Numpad8 => KeyboardKey.Numpad8,
        Keys.Numpad9 => KeyboardKey.Numpad9,
        Keys.NumpadDecimal => KeyboardKey.NumpadDecimal,
        Keys.NumpadDivide => KeyboardKey.NumpadDivide,
        Keys.NumpadMultiply => KeyboardKey.NumpadMultiply,
        Keys.NumpadSubtract => KeyboardKey.NumpadSubtract,
        Keys.NumpadAdd => KeyboardKey.NumpadAdd,
        Keys.NumpadEnter => KeyboardKey.NumpadEnter,
        Keys.NumpadEqual => KeyboardKey.NumpadEquals,

        Keys.LeftShift => KeyboardKey.LeftShift,
        Keys.LeftControl => KeyboardKey.LeftControl,
        Keys.LeftAlt => KeyboardKey.LeftAlt,
        Keys.LeftSuper => KeyboardKey.LeftSuper,
        Keys.RightShift => KeyboardKey.RightShift,
        Keys.RightControl => KeyboardKey.RightControl,
        Keys.RightAlt => KeyboardKey.RightAlt,
        Keys.RightSuper => KeyboardKey.RightSuper,
        Keys.Menu => KeyboardKey.Menu,

        _ => KeyboardKey.Unknown,
    };
}
