// Metal backend for RenderedCanvasBase.
//
// Pipeline:
//   - Three MTLRenderPipelineState (rect, glyph, image) built from
//     .gen.metal generated by tools/CompileCanvasShaders.
//   - Per-frame instance buffers (Shared storage), refreshed via diff-upload
//     from the base class.
//   - One Globals UBO (projection mat4) + one ClipRects UBO (256 vec4),
//     bound to buffer slots 0 and 1 respectively (matches Slang output).
//   - One R8Unorm atlas texture for fonts.
//   - One linear-clamp sampler shared by all draws.
//
// Lifecycle: MetalApp owns the drawable/command buffer/encoder; the canvas's
// EndFrame(encoder) overload issues all draws into the supplied encoder. The
// CPU/GPU sync is wait-for-prior-frame at the top of EndFrame: we wait for
// the previously-committed command buffer to finish before mutating any
// Shared-storage buffer, since the GPU may still be reading them.

using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using ZGF.Core.MacOs;
using ZGF.Fonts;
using ZGF.Geometry;
using ZGF.Gui;
using static ZGF.Core.MacOs.Objc;

namespace ZGF.Gui.Tests;

public sealed unsafe class MetalRenderedCanvas : RenderedCanvasBase, IDisposable
{
    private readonly IntPtr _device;
    private readonly MetalImageManager _imageManager;

    private IntPtr _rectPipeline;
    private IntPtr _glyphPipeline;
    private IntPtr _imagePipeline;

    private IntPtr _unitQuadBuffer;          // 12 floats, 6 vertices, per-vertex
    private IntPtr _rectInstanceBuffer;
    private IntPtr _glyphInstanceBuffer;
    private IntPtr _imageInstanceBuffer;
    private IntPtr _globalsBuffer;           // projection matrix (mat4)
    private IntPtr _clipBuffer;              // 256 * vec4
    private IntPtr _samplerState;
    private IntPtr _atlasTexture;

    private Matrix4x4 _projection;
    private IntPtr _pendingCommandBuffer;    // last frame's command buffer (await before mutating shared buffers)

    public MetalRenderedCanvas(
        int width, int height,
        FreeTypeFontBackend fonts, FontHandle defaultFont,
        MetalImageManager imageManager,
        IntPtr device)
        : base(width, height, fonts, defaultFont)
    {
        _device = device;
        _imageManager = imageManager;

        _projection = Matrix4x4.CreateOrthographicOffCenter(0, width, 0, height, -1f, 1f);

        var library = LoadLibrary(device,
            File.ReadAllText(Path.Combine(AppContext.BaseDirectory, "Assets", "Shaders", "canvas_rect.gen.metal")));
        _rectPipeline = BuildPipeline(device, library, MakeRectVertexDescriptor());
        Release(library);

        library = LoadLibrary(device,
            File.ReadAllText(Path.Combine(AppContext.BaseDirectory, "Assets", "Shaders", "canvas_glyph.gen.metal")));
        _glyphPipeline = BuildPipeline(device, library, MakeGlyphVertexDescriptor());
        Release(library);

        library = LoadLibrary(device,
            File.ReadAllText(Path.Combine(AppContext.BaseDirectory, "Assets", "Shaders", "canvas_image.gen.metal")));
        _imagePipeline = BuildPipeline(device, library, MakeImageVertexDescriptor());
        Release(library);

        _unitQuadBuffer = MakeUnitQuadBuffer(device);
        _rectInstanceBuffer = NewSharedBuffer(device, MaxRects * sizeof(RectInstance));
        _glyphInstanceBuffer = NewSharedBuffer(device, MaxGlyphs * sizeof(GlyphInstance));
        _imageInstanceBuffer = NewSharedBuffer(device, MaxImages * sizeof(ImageInstance));
        _globalsBuffer = NewSharedBuffer(device, sizeof(Matrix4x4));
        _clipBuffer = NewSharedBuffer(device, MaxClips * sizeof(Vector4));

        UploadProjectionToBuffer();

        _samplerState = BuildLinearClampSampler(device);
        _atlasTexture = SetupFontAtlasTexture(device, FontBackend);
    }

    /// <summary>
    /// Per-frame Metal lifecycle. The caller is responsible for acquiring the
    /// drawable, building the command buffer + render encoder, and presenting.
    /// EndFrame(encoder) runs the shared sort/batch/upload pipeline then
    /// issues draws into the supplied encoder.
    /// </summary>
    public void EndFrame(IntPtr renderCommandEncoder, IntPtr currentCommandBuffer)
    {
        // Wait for the prior frame's command buffer (if any) to finish on the
        // GPU before we mutate shared-storage buffers. Without this, the GPU
        // could read torn data mid-frame.
        if (_pendingCommandBuffer != IntPtr.Zero)
        {
            msg_Void(_pendingCommandBuffer, Sel("waitUntilCompleted"));
            Release(_pendingCommandBuffer);
            _pendingCommandBuffer = IntPtr.Zero;
        }

        _currentEncoder = renderCommandEncoder;
        base.EndFrame();
        _currentEncoder = IntPtr.Zero;

        // Retain so we can wait on it next frame.
        if (currentCommandBuffer != IntPtr.Zero)
        {
            Retain(currentCommandBuffer);
            _pendingCommandBuffer = currentCommandBuffer;
        }
    }

    // RenderedCanvasBase calls IssueDraws() at the end of EndFrame(); we
    // route into the encoder that EndFrame(encoder, cb) parked here.
    private IntPtr _currentEncoder;

    protected override void OnResize(int width, int height)
    {
        _projection = Matrix4x4.CreateOrthographicOffCenter(0, width, 0, height, -1f, 1f);
        UploadProjectionToBuffer();
    }

    protected override Size GetImageSizeImpl(string imageId) => _imageManager.GetImageSize(imageId);
    protected override uint GetImageTextureId(string imageId) => _imageManager.GetTextureId(imageId);

    protected override void UploadRectInstances(RectInstance[] data, int count)
    {
        if (count == 0) return;
        var dst = (RectInstance*)msg_IntPtr(_rectInstanceBuffer, Sel("contents"));
        fixed (RectInstance* src = &data[0])
            Buffer.MemoryCopy(src, dst, MaxRects * sizeof(RectInstance), count * sizeof(RectInstance));
    }

    protected override void UploadGlyphInstances(GlyphInstance[] data, int count)
    {
        if (count == 0) return;
        var dst = (GlyphInstance*)msg_IntPtr(_glyphInstanceBuffer, Sel("contents"));
        fixed (GlyphInstance* src = &data[0])
            Buffer.MemoryCopy(src, dst, MaxGlyphs * sizeof(GlyphInstance), count * sizeof(GlyphInstance));
    }

    protected override void UploadImageInstances(ImageInstance[] data, int count)
    {
        if (count == 0) return;
        var dst = (ImageInstance*)msg_IntPtr(_imageInstanceBuffer, Sel("contents"));
        fixed (ImageInstance* src = &data[0])
            Buffer.MemoryCopy(src, dst, MaxImages * sizeof(ImageInstance), count * sizeof(ImageInstance));
    }

    protected override void UploadClips(List<Vector4> clips)
    {
        if (clips.Count == 0) return;
        var dst = (Vector4*)msg_IntPtr(_clipBuffer, Sel("contents"));
        for (var i = 0; i < clips.Count; i++) dst[i] = clips[i];
    }

    protected override void UpdateAtlasIfDirty()
    {
        var fonts = FontBackend;
        if (!fonts.AtlasDirty) return;

        var rect = fonts.DirtyRect;
        if (rect.IsEmpty)
        {
            fonts.ClearDirty();
            return;
        }

        var pixels = fonts.AtlasPixels;
        var region = new MTLRegion
        {
            Origin = new MTLOrigin { X = (nuint)rect.X, Y = (nuint)rect.Y, Z = 0 },
            Size = new MTLSize { Width = (nuint)rect.Width, Height = (nuint)rect.Height, Depth = 1 },
        };

        fixed (byte* basePtr = &MemoryMarshal.GetReference(pixels))
        {
            var atlasW = fonts.AtlasWidth;
            var srcPtr = basePtr + (rect.Y * atlasW + rect.X);
            msg_Void_MTLRegion_NUInt_IntPtr_NUInt(
                _atlasTexture, Sel("replaceRegion:mipmapLevel:withBytes:bytesPerRow:"),
                region, 0, (IntPtr)srcPtr, (nuint)atlasW);
        }

        fonts.ClearDirty();
        LastFrameUploadCount++;
    }

    protected override void IssueDraws(IReadOnlyList<DrawCall> drawCalls)
    {
        if (_currentEncoder == IntPtr.Zero || drawCalls.Count == 0)
            return;

        var enc = _currentEncoder;
        DrawKind boundKind = (DrawKind)255;
        IntPtr boundTexture = IntPtr.Zero;

        // Constant-buffer bindings (slot 0=Globals, slot 1=ClipRects) are set
        // once per kind change since the same pipeline gets re-used.
        var setVertexBufferSel = Sel("setVertexBuffer:offset:atIndex:");
        var setFragmentBufferSel = Sel("setFragmentBuffer:offset:atIndex:");
        var setVertexTextureSel = Sel("setVertexTexture:atIndex:");
        var setFragmentTextureSel = Sel("setFragmentTexture:atIndex:");
        var setFragmentSamplerSel = Sel("setFragmentSamplerState:atIndex:");
        var setPipelineSel = Sel("setRenderPipelineState:");
        var drawPrimSel = Sel("drawPrimitives:vertexStart:vertexCount:instanceCount:");

        for (var i = 0; i < drawCalls.Count; i++)
        {
            var call = drawCalls[i];

            if (call.Kind != boundKind)
            {
                IntPtr pipeline = call.Kind switch
                {
                    DrawKind.Rect => _rectPipeline,
                    DrawKind.Glyph => _glyphPipeline,
                    DrawKind.Image => _imagePipeline,
                    _ => IntPtr.Zero,
                };
                msg_Void_IntPtr(enc, setPipelineSel, pipeline);

                // Globals (slot 0), ClipRects (slot 1) — both vertex and fragment use them.
                msg_Void_IntPtr_NUInt_NUInt(enc, setVertexBufferSel, _globalsBuffer, 0, 0);
                msg_Void_IntPtr_NUInt_NUInt(enc, setFragmentBufferSel, _globalsBuffer, 0, 0);
                msg_Void_IntPtr_NUInt_NUInt(enc, setVertexBufferSel, _clipBuffer, 0, 1);
                msg_Void_IntPtr_NUInt_NUInt(enc, setFragmentBufferSel, _clipBuffer, 0, 1);

                // Per-vertex unit quad at slot 2.
                msg_Void_IntPtr_NUInt_NUInt(enc, setVertexBufferSel, _unitQuadBuffer, 0, 2);

                // Per-instance buffer + texture/sampler bindings per kind.
                switch (call.Kind)
                {
                    case DrawKind.Rect:
                        msg_Void_IntPtr_NUInt_NUInt(enc, setVertexBufferSel, _rectInstanceBuffer, 0, 3);
                        break;
                    case DrawKind.Glyph:
                        msg_Void_IntPtr_NUInt_NUInt(enc, setVertexBufferSel, _glyphInstanceBuffer, 0, 3);
                        msg_Void_IntPtr_NUInt(enc, setFragmentTextureSel, _atlasTexture, 0);
                        msg_Void_IntPtr_NUInt(enc, setFragmentSamplerSel, _samplerState, 0);
                        boundTexture = _atlasTexture;
                        break;
                    case DrawKind.Image:
                        msg_Void_IntPtr_NUInt_NUInt(enc, setVertexBufferSel, _imageInstanceBuffer, 0, 3);
                        msg_Void_IntPtr_NUInt(enc, setFragmentSamplerSel, _samplerState, 0);
                        boundTexture = IntPtr.Zero;
                        break;
                }

                boundKind = call.Kind;
            }

            if (call.Kind == DrawKind.Image)
            {
                var tex = _imageManager.GetMetalTexture(call.TextureId);
                if (tex != boundTexture)
                {
                    msg_Void_IntPtr_NUInt(enc, setFragmentTextureSel, tex, 0);
                    boundTexture = tex;
                }
            }

            // drawPrimitives: triangles, vertexStart=0, vertexCount=6, instanceCount=N.
            // Slang's vertex stage indexes the instance via [[instance_id]]; the base
            // instance offset is folded in via the buffer's bind offset (set above as 0).
            // For sub-ranges we rebind the buffer at the call's start offset.
            if (call.InstanceStart > 0)
            {
                var (buf, stride) = call.Kind switch
                {
                    DrawKind.Rect => (_rectInstanceBuffer, sizeof(RectInstance)),
                    DrawKind.Glyph => (_glyphInstanceBuffer, sizeof(GlyphInstance)),
                    DrawKind.Image => (_imageInstanceBuffer, sizeof(ImageInstance)),
                    _ => (IntPtr.Zero, 0),
                };
                msg_Void_IntPtr_NUInt_NUInt(enc, setVertexBufferSel, buf, (nuint)(call.InstanceStart * stride), 3);
            }
            else if (call.Kind != boundKind) // already bound at offset 0 above
            { }

            msg_Void_MTLPrim_NUInt_NUInt_NUInt(enc, drawPrimSel,
                (nuint)MTLPrimitiveType.Triangle, 0, 6, (nuint)call.InstanceCount);

            // If we rebound at an offset, reset back to 0 for the next call of the same kind.
            if (call.InstanceStart > 0)
            {
                var buf = call.Kind switch
                {
                    DrawKind.Rect => _rectInstanceBuffer,
                    DrawKind.Glyph => _glyphInstanceBuffer,
                    DrawKind.Image => _imageInstanceBuffer,
                    _ => IntPtr.Zero,
                };
                msg_Void_IntPtr_NUInt_NUInt(enc, setVertexBufferSel, buf, 0, 3);
            }
        }
    }

    private void UploadProjectionToBuffer()
    {
        if (_globalsBuffer == IntPtr.Zero) return;
        var dst = (Matrix4x4*)msg_IntPtr(_globalsBuffer, Sel("contents"));
        // Slang emits `v * M` in MSL for HLSL's `mul(M, v)`, which treats v as a
        // row vector and reads M column-major. System.Numerics.Matrix4x4 is laid
        // out row-vec/row-major; upload the transpose so v · M reproduces M · v.
        *dst = Matrix4x4.Transpose(_projection);
    }

    // ---------- Metal setup helpers ----------

    private static IntPtr LoadLibrary(IntPtr device, string source)
    {
        // newLibraryWithSource:options:error: returns id<MTLLibrary>.
        var nsString = NSString(source);
        IntPtr error = IntPtr.Zero;
        var sel = Sel("newLibraryWithSource:options:error:");
        var library = msg_NewLibrary(device, sel, nsString, IntPtr.Zero, ref error);
        Release(nsString);
        if (library == IntPtr.Zero)
        {
            var msg = error != IntPtr.Zero ? NSStringToManaged(msg_IntPtr(error, Sel("localizedDescription"))) : "(no error)";
            throw new Exception($"newLibraryWithSource failed: {msg}");
        }
        return library;
    }

    [DllImport("/usr/lib/libobjc.A.dylib", EntryPoint = "objc_msgSend")]
    private static extern IntPtr msg_NewLibrary(IntPtr receiver, IntPtr selector, IntPtr source, IntPtr options, ref IntPtr error);

    private static IntPtr NSString(string s)
    {
        var cls = Class("NSString");
        var alloc = msg_IntPtr(cls, Sel("alloc"));
        var bytes = System.Text.Encoding.UTF8.GetBytes(s);
        fixed (byte* p = bytes)
        {
            // initWithBytes:length:encoding: with NSUTF8StringEncoding (4).
            return InitWithBytes(alloc, Sel("initWithBytes:length:encoding:"), (IntPtr)p, (nuint)bytes.Length, 4);
        }
    }

    [DllImport("/usr/lib/libobjc.A.dylib", EntryPoint = "objc_msgSend")]
    private static extern IntPtr InitWithBytes(IntPtr receiver, IntPtr selector, IntPtr bytes, nuint length, nuint encoding);

    private static string NSStringToManaged(IntPtr nsString)
    {
        if (nsString == IntPtr.Zero) return "";
        var utf8 = msg_IntPtr(nsString, Sel("UTF8String"));
        return Marshal.PtrToStringUTF8(utf8) ?? "";
    }

    private static IntPtr BuildPipeline(IntPtr device, IntPtr library, IntPtr vertexDescriptor)
    {
        var vsName = NSString("vertexMain");
        var fsName = NSString("fragmentMain");
        var vs = msg_IntPtr(library, Sel("newFunctionWithName:"), vsName);
        var fs = msg_IntPtr(library, Sel("newFunctionWithName:"), fsName);
        Release(vsName);
        Release(fsName);
        if (vs == IntPtr.Zero || fs == IntPtr.Zero)
            throw new Exception("Could not find vertexMain/fragmentMain in compiled library.");

        var descClass = Class("MTLRenderPipelineDescriptor");
        var desc = New(descClass);
        msg_Void_IntPtr(desc, Sel("setVertexFunction:"), vs);
        msg_Void_IntPtr(desc, Sel("setFragmentFunction:"), fs);
        msg_Void_IntPtr(desc, Sel("setVertexDescriptor:"), vertexDescriptor);

        // colorAttachments[0]: BGRA8Unorm + alpha blending.
        var colorAttachments = msg_IntPtr(desc, Sel("colorAttachments"));
        var color0 = msg_IntPtr_NUInt_NUInt(colorAttachments, Sel("objectAtIndexedSubscript:"), 0, 0);
        msg_Void_UInt(color0, Sel("setPixelFormat:"), (uint)MTLPixelFormat.BGRA8Unorm);
        msg_Void_Bool(color0, Sel("setBlendingEnabled:"), true);
        // 0=Add, 4=SrcAlpha, 5=OneMinusSrcAlpha, 1=One (for alpha)
        msg_Void_UInt(color0, Sel("setRgbBlendOperation:"), 0);
        msg_Void_UInt(color0, Sel("setAlphaBlendOperation:"), 0);
        msg_Void_UInt(color0, Sel("setSourceRGBBlendFactor:"), 4);
        msg_Void_UInt(color0, Sel("setSourceAlphaBlendFactor:"), 4);
        msg_Void_UInt(color0, Sel("setDestinationRGBBlendFactor:"), 5);
        msg_Void_UInt(color0, Sel("setDestinationAlphaBlendFactor:"), 5);

        IntPtr error = IntPtr.Zero;
        var pipeline = msg_NewLibrary(device, Sel("newRenderPipelineStateWithDescriptor:error:"), desc, IntPtr.Zero, ref error);
        Release(desc);
        Release(vs);
        Release(fs);
        if (pipeline == IntPtr.Zero)
        {
            var msg = error != IntPtr.Zero ? NSStringToManaged(msg_IntPtr(error, Sel("localizedDescription"))) : "(no error)";
            throw new Exception($"newRenderPipelineStateWithDescriptor failed: {msg}");
        }
        return pipeline;
    }

    // ---------- Vertex descriptors ----------

    private static IntPtr MakeRectVertexDescriptor()
    {
        var desc = MakeVertexDescriptorBase();
        // attribute 0 unitPos vec2 at buffer 2 offset 0
        SetAttribute(desc, 0, MTLVertexFormat.Float2, 0, 2);
        // instance attribs at buffer 3
        var off = 0;
        SetAttribute(desc, 1, MTLVertexFormat.Float4, off, 3); off += 16;
        SetAttribute(desc, 2, MTLVertexFormat.Float4, off, 3); off += 16;
        SetAttribute(desc, 3, MTLVertexFormat.Float4, off, 3); off += 16;
        SetAttribute(desc, 4, MTLVertexFormat.UInt, off, 3); off += 4;
        SetAttribute(desc, 5, MTLVertexFormat.UInt, off, 3); off += 4;
        SetAttribute(desc, 6, MTLVertexFormat.UInt, off, 3); off += 4;
        SetAttribute(desc, 7, MTLVertexFormat.UInt, off, 3); off += 4;
        SetAttribute(desc, 8, MTLVertexFormat.UInt, off, 3); off += 4;
        SetAttribute(desc, 9, MTLVertexFormat.UInt, off, 3); off += 4;
        SetLayout(desc, 2, 8, MTLVertexStepFunction.PerVertex);
        SetLayout(desc, 3, sizeof(RectInstance), MTLVertexStepFunction.PerInstance);
        return desc;
    }

    private static IntPtr MakeGlyphVertexDescriptor()
    {
        var desc = MakeVertexDescriptorBase();
        SetAttribute(desc, 0, MTLVertexFormat.Float2, 0, 2);
        var off = 0;
        SetAttribute(desc, 1, MTLVertexFormat.Float4, off, 3); off += 16;
        SetAttribute(desc, 2, MTLVertexFormat.Float4, off, 3); off += 16;
        SetAttribute(desc, 3, MTLVertexFormat.UInt, off, 3); off += 4;
        SetAttribute(desc, 4, MTLVertexFormat.UInt, off, 3); off += 4;
        SetLayout(desc, 2, 8, MTLVertexStepFunction.PerVertex);
        SetLayout(desc, 3, sizeof(GlyphInstance), MTLVertexStepFunction.PerInstance);
        return desc;
    }

    private static IntPtr MakeImageVertexDescriptor()
    {
        var desc = MakeVertexDescriptorBase();
        SetAttribute(desc, 0, MTLVertexFormat.Float2, 0, 2);
        var off = 0;
        SetAttribute(desc, 1, MTLVertexFormat.Float4, off, 3); off += 16;
        SetAttribute(desc, 2, MTLVertexFormat.Float4, off, 3); off += 16;
        SetAttribute(desc, 3, MTLVertexFormat.UInt, off, 3); off += 4;
        SetAttribute(desc, 4, MTLVertexFormat.UInt, off, 3); off += 4;
        SetAttribute(desc, 5, MTLVertexFormat.Float, off, 3); off += 4;
        SetLayout(desc, 2, 8, MTLVertexStepFunction.PerVertex);
        SetLayout(desc, 3, sizeof(ImageInstance), MTLVertexStepFunction.PerInstance);
        return desc;
    }

    private static IntPtr MakeVertexDescriptorBase() => New(Class("MTLVertexDescriptor"));

    private static void SetAttribute(IntPtr desc, uint index, MTLVertexFormat format, int offset, int bufferIndex)
    {
        var attribs = msg_IntPtr(desc, Sel("attributes"));
        var attrib = msg_IntPtr_NUInt_NUInt(attribs, Sel("objectAtIndexedSubscript:"), index, 0);
        msg_Void_UInt(attrib, Sel("setFormat:"), (uint)format);
        msg_Void_NUInt_NUInt(attrib, Sel("setOffset:"), (nuint)offset, 0);
        msg_Void_NUInt_NUInt(attrib, Sel("setBufferIndex:"), (nuint)bufferIndex, 0);
    }

    private static void SetLayout(IntPtr desc, uint bufferIndex, int stride, MTLVertexStepFunction step)
    {
        var layouts = msg_IntPtr(desc, Sel("layouts"));
        var layout = msg_IntPtr_NUInt_NUInt(layouts, Sel("objectAtIndexedSubscript:"), bufferIndex, 0);
        msg_Void_NUInt_NUInt(layout, Sel("setStride:"), (nuint)stride, 0);
        msg_Void_UInt(layout, Sel("setStepFunction:"), (uint)step);
    }

    private static IntPtr MakeUnitQuadBuffer(IntPtr device)
    {
        Span<float> verts = stackalloc float[12]
        {
            0f, 0f,
            1f, 0f,
            0f, 1f,
            1f, 0f,
            1f, 1f,
            0f, 1f,
        };
        var byteLen = verts.Length * sizeof(float);
        fixed (float* p = &verts[0])
        {
            return NewBufferWithBytes(device, Sel("newBufferWithBytes:length:options:"),
                (IntPtr)p, (nuint)byteLen, (nuint)MTLResourceOptions.StorageModeShared);
        }
    }

    [DllImport("/usr/lib/libobjc.A.dylib", EntryPoint = "objc_msgSend")]
    private static extern IntPtr NewBufferWithBytes(IntPtr receiver, IntPtr selector, IntPtr bytes, nuint length, nuint options);

    [DllImport("/usr/lib/libobjc.A.dylib", EntryPoint = "objc_msgSend")]
    private static extern IntPtr NewBufferLength(IntPtr receiver, IntPtr selector, nuint length, nuint options);

    private static IntPtr NewSharedBuffer(IntPtr device, int byteLen)
    {
        return NewBufferLength(device, Sel("newBufferWithLength:options:"), (nuint)byteLen, (nuint)MTLResourceOptions.StorageModeShared);
    }

    private static IntPtr BuildLinearClampSampler(IntPtr device)
    {
        var descClass = Class("MTLSamplerDescriptor");
        var desc = New(descClass);
        msg_Void_UInt(desc, Sel("setMinFilter:"), (uint)MTLSamplerMinMagFilter.Linear);
        msg_Void_UInt(desc, Sel("setMagFilter:"), (uint)MTLSamplerMinMagFilter.Linear);
        msg_Void_UInt(desc, Sel("setSAddressMode:"), (uint)MTLSamplerAddressMode.ClampToEdge);
        msg_Void_UInt(desc, Sel("setTAddressMode:"), (uint)MTLSamplerAddressMode.ClampToEdge);
        var sampler = msg_IntPtr(device, Sel("newSamplerStateWithDescriptor:"), desc);
        Release(desc);
        return sampler;
    }

    private static IntPtr SetupFontAtlasTexture(IntPtr device, FreeTypeFontBackend fonts)
    {
        var width = fonts.AtlasWidth;
        var height = fonts.AtlasHeight;
        var pixels = fonts.AtlasPixels;

        var descClass = Class("MTLTextureDescriptor");
        var desc = TextureDescriptor2D(descClass,
            Sel("texture2DDescriptorWithPixelFormat:width:height:mipmapped:"),
            (nuint)MTLPixelFormat.R8Unorm, (nuint)width, (nuint)height, false);
        msg_Void_UInt(desc, Sel("setStorageMode:"), (uint)MTLStorageMode.Shared);
        msg_Void_UInt(desc, Sel("setUsage:"), (uint)MTLTextureUsage.ShaderRead);

        var tex = msg_IntPtr(device, Sel("newTextureWithDescriptor:"), desc);
        var region = new MTLRegion
        {
            Origin = new MTLOrigin(),
            Size = new MTLSize { Width = (nuint)width, Height = (nuint)height, Depth = 1 },
        };
        fixed (byte* p = &MemoryMarshal.GetReference(pixels))
        {
            msg_Void_MTLRegion_NUInt_IntPtr_NUInt(tex,
                Sel("replaceRegion:mipmapLevel:withBytes:bytesPerRow:"),
                region, 0, (IntPtr)p, (nuint)width);
        }
        fonts.ClearDirty();
        return tex;
    }

    [DllImport("/usr/lib/libobjc.A.dylib", EntryPoint = "objc_msgSend")]
    private static extern IntPtr TextureDescriptor2D(
        IntPtr receiver, IntPtr selector,
        nuint pixelFormat, nuint width, nuint height,
        [MarshalAs(UnmanagedType.I1)] bool mipmapped);

    public void Dispose()
    {
        Release(_atlasTexture);
        Release(_samplerState);
        Release(_clipBuffer);
        Release(_globalsBuffer);
        Release(_imageInstanceBuffer);
        Release(_glyphInstanceBuffer);
        Release(_rectInstanceBuffer);
        Release(_unitQuadBuffer);
        Release(_imagePipeline);
        Release(_glyphPipeline);
        Release(_rectPipeline);
        if (_pendingCommandBuffer != IntPtr.Zero)
        {
            Release(_pendingCommandBuffer);
            _pendingCommandBuffer = IntPtr.Zero;
        }
    }
}
