using System.Collections.Immutable;
using System.Text;

namespace ZGF.Observable.Generators;

internal static class Emitter
{
    public static string Emit(
        string @namespace,
        string typeKeyword,
        string typeName,
        string typeAccessibility,
        ImmutableArray<PropertyModel> properties)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using global::ZGF.Observable;");
        sb.AppendLine();

        var indent = "";
        if (!string.IsNullOrEmpty(@namespace))
        {
            sb.Append("namespace ").Append(@namespace).AppendLine();
            sb.AppendLine("{");
            indent = "    ";
        }

        sb.Append(indent).Append(typeAccessibility);
        if (!string.IsNullOrEmpty(typeAccessibility)) sb.Append(' ');
        sb.Append("partial ").Append(typeKeyword).Append(' ').Append(typeName).AppendLine();
        sb.Append(indent).AppendLine("{");

        var memberIndent = indent + "    ";

        for (var i = 0; i < properties.Length; i++)
        {
            var p = properties[i];
            EmitProperty(sb, memberIndent, p);
            if (i < properties.Length - 1) sb.AppendLine();
        }

        sb.Append(indent).AppendLine("}");

        if (!string.IsNullOrEmpty(@namespace))
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private static void EmitProperty(StringBuilder sb, string indent, PropertyModel p)
    {
        var stateFieldName = "__" + ToFieldCase(p.PropertyName) + "_state";
        var stateAccessorName = "__" + ToFieldCase(p.PropertyName);
        var stateType = "global::ZGF.Observable.State<" + p.PropertyTypeDisplay + ">";

        string initialExpression;
        if (p.HasDefaultMethod)
        {
            initialExpression = p.DefaultMethodName + "()";
        }
        else if (p.HasAttributeInitial && p.AttributeInitialLiteral is not null)
        {
            initialExpression = p.AttributeInitialLiteral;
        }
        else
        {
            initialExpression = "default!";
        }

        sb.Append(indent).Append("private ").Append(stateType).Append("? ").Append(stateFieldName).AppendLine(";");
        sb.Append(indent).Append("private ").Append(stateType).Append(' ').Append(stateAccessorName)
            .Append(" => ").Append(stateFieldName).Append(" ??= Property<")
            .Append(p.PropertyTypeDisplay).Append(">(").Append(initialExpression).AppendLine(");");

        sb.AppendLine();

        sb.Append(indent).Append(p.PropertyAccessibility);
        if (!string.IsNullOrEmpty(p.PropertyAccessibility)) sb.Append(' ');
        sb.Append("partial ").Append(p.PropertyTypeDisplay).Append(' ').Append(p.PropertyName).AppendLine();
        sb.Append(indent).AppendLine("{");

        var bodyIndent = indent + "    ";
        sb.Append(bodyIndent);
        if (!string.IsNullOrEmpty(p.GetAccessibility) && p.GetAccessibility != p.PropertyAccessibility)
            sb.Append(p.GetAccessibility).Append(' ');
        sb.Append("get => ").Append(stateAccessorName).AppendLine(".Value;");

        sb.Append(bodyIndent);
        if (!string.IsNullOrEmpty(p.SetAccessibility) && p.SetAccessibility != p.PropertyAccessibility)
            sb.Append(p.SetAccessibility).Append(' ');
        sb.Append("set => ").Append(stateAccessorName).AppendLine(".Value = value;");

        sb.Append(indent).AppendLine("}");

        sb.AppendLine();

        sb.Append(indent).Append("public global::System.IDisposable Observe").Append(p.PropertyName)
            .Append("(global::System.Action<").Append(p.PropertyTypeDisplay).Append("> handler) => ")
            .Append(stateAccessorName).AppendLine(".Subscribe(handler);");
    }

    private static string ToFieldCase(string propertyName)
    {
        if (string.IsNullOrEmpty(propertyName)) return propertyName;
        if (char.IsUpper(propertyName[0]))
            return char.ToLowerInvariant(propertyName[0]) + propertyName.Substring(1);
        return propertyName;
    }
}
