using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ZGF.Observable.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class ObservablePropertyGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "ZGF.Observable.ObservableAttribute";
    private const string AttributeSource = """
        // <auto-generated/>
        #nullable enable

        namespace ZGF.Observable;

        [global::System.AttributeUsage(global::System.AttributeTargets.Property, AllowMultiple = false)]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        internal sealed class ObservableAttribute : global::System.Attribute
        {
            public ObservableAttribute() { }
            public ObservableAttribute(object initialValue)
            {
                InitialValue = initialValue;
                HasInitialValue = true;
            }
            public object? InitialValue { get; }
            public bool HasInitialValue { get; }
        }
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource("ObservableAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8));
        });

        var properties = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is PropertyDeclarationSyntax,
                transform: static (ctx, _) => Collect(ctx))
            .Where(static p => p is not null)
            .Select(static (p, _) => p!);

        var grouped = properties.Collect();

        context.RegisterSourceOutput(grouped, static (spc, props) =>
        {
            foreach (var diag in props.SelectMany(p => p.Diagnostics))
            {
                spc.ReportDiagnostic(diag);
            }

            var byType = props
                .Where(p => p.IsValid)
                .GroupBy(p => p.ContainingTypeKey, p => p);

            foreach (var group in byType)
            {
                var first = group.First();
                var source = Emitter.Emit(first.Namespace, first.TypeDeclarationKeyword, first.TypeName, first.TypeAccessibility, group.ToImmutableArray());
                var fileName = (string.IsNullOrEmpty(first.Namespace) ? first.TypeName : $"{first.Namespace}.{first.TypeName}") + ".Observable.g.cs";
                spc.AddSource(fileName, SourceText.From(source, Encoding.UTF8));
            }
        });
    }

    private static PropertyModel? Collect(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not IPropertySymbol propertySymbol) return null;
        if (ctx.TargetNode is not PropertyDeclarationSyntax propSyntax) return null;
        var containingType = propertySymbol.ContainingType;
        if (containingType is null) return null;

        var diags = new List<Diagnostic>();

        var isPartialProperty = propSyntax.Modifiers.Any(m => m.ValueText == "partial");
        if (!isPartialProperty)
        {
            diags.Add(Diagnostic.Create(Diagnostics.PropertyNotPartial, propSyntax.Identifier.GetLocation(), propertySymbol.Name));
        }

        var hasGet = propertySymbol.GetMethod is not null;
        var hasSet = propertySymbol.SetMethod is not null;
        if (!(hasGet && hasSet))
        {
            diags.Add(Diagnostic.Create(Diagnostics.PropertyMissingAccessors, propSyntax.Identifier.GetLocation(), propertySymbol.Name));
        }

        var typeDeclSyntax = propSyntax.FirstAncestorOrSelf<TypeDeclarationSyntax>();
        var isContainingPartial = typeDeclSyntax is not null
            && typeDeclSyntax.Modifiers.Any(m => m.ValueText == "partial");
        if (!isContainingPartial)
        {
            var loc = typeDeclSyntax?.Identifier.GetLocation() ?? propSyntax.Identifier.GetLocation();
            diags.Add(Diagnostic.Create(Diagnostics.ContainingTypeNotPartial, loc, containingType.Name));
        }

        var isView = InheritsFromView(containingType);
        if (!isView)
        {
            var loc = typeDeclSyntax?.Identifier.GetLocation() ?? propSyntax.Identifier.GetLocation();
            diags.Add(Diagnostic.Create(Diagnostics.ContainingTypeNotView, loc, containingType.Name));
        }

        var attr = propertySymbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == AttributeFullName);
        var hasAttributeInitial = false;
        string? attributeInitialLiteral = null;
        if (attr is not null && attr.ConstructorArguments.Length == 1)
        {
            hasAttributeInitial = true;
            attributeInitialLiteral = FormatConstant(attr.ConstructorArguments[0]);
        }

        var propertyTypeDisplay = propertySymbol.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        var defaultMethodName = "Default" + propertySymbol.Name;
        var hasDefaultMethod = false;
        foreach (var member in containingType.GetMembers(defaultMethodName))
        {
            if (member is IMethodSymbol m && m.Parameters.Length == 0 && !m.IsStatic)
            {
                hasDefaultMethod = true;
                var returnTypeDisplay = m.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                if (!SymbolEqualityComparer.Default.Equals(m.ReturnType, propertySymbol.Type))
                {
                    diags.Add(Diagnostic.Create(
                        Diagnostics.DefaultMethodTypeMismatch,
                        m.Locations.FirstOrDefault() ?? propSyntax.Identifier.GetLocation(),
                        propertySymbol.Name,
                        returnTypeDisplay,
                        propertyTypeDisplay));
                }
                break;
            }
        }

        if (hasAttributeInitial && hasDefaultMethod)
        {
            diags.Add(Diagnostic.Create(Diagnostics.AmbiguousInitialValue, propSyntax.Identifier.GetLocation(), propertySymbol.Name));
        }

        var getAccessibility = propertySymbol.GetMethod is { } gm
            ? FormatAccessibility(gm.DeclaredAccessibility, propertySymbol.DeclaredAccessibility)
            : "";
        var setAccessibility = propertySymbol.SetMethod is { } sm
            ? FormatAccessibility(sm.DeclaredAccessibility, propertySymbol.DeclaredAccessibility)
            : "";

        var propertyAccessibility = FormatAccessibility(propertySymbol.DeclaredAccessibility, Accessibility.Internal);

        var ns = containingType.ContainingNamespace is { IsGlobalNamespace: false }
            ? containingType.ContainingNamespace.ToDisplayString()
            : "";

        var typeName = containingType.Name;
        var typeKeyword = typeDeclSyntax switch
        {
            ClassDeclarationSyntax => "class",
            RecordDeclarationSyntax r => r.ClassOrStructKeyword.ValueText == "struct" ? "record struct" : "record",
            StructDeclarationSyntax => "struct",
            _ => "class",
        };

        var typeAccessibility = FormatAccessibility(containingType.DeclaredAccessibility, Accessibility.Internal);

        return new PropertyModel(
            ContainingTypeKey: (ns, typeName),
            Namespace: ns,
            TypeName: typeName,
            TypeDeclarationKeyword: typeKeyword,
            TypeAccessibility: typeAccessibility,
            PropertyName: propertySymbol.Name,
            PropertyTypeDisplay: propertyTypeDisplay,
            PropertyAccessibility: propertyAccessibility,
            GetAccessibility: getAccessibility,
            SetAccessibility: setAccessibility,
            HasAttributeInitial: hasAttributeInitial,
            AttributeInitialLiteral: attributeInitialLiteral,
            HasDefaultMethod: hasDefaultMethod,
            DefaultMethodName: defaultMethodName,
            IsValid: diags.Count == 0,
            Diagnostics: diags.ToImmutableArray());
    }

    private static bool InheritsFromView(INamedTypeSymbol type)
    {
        for (var cur = type; cur is not null; cur = cur.BaseType)
        {
            if (cur.Name == "View" && cur.ContainingNamespace?.ToDisplayString() == "ZGF.Gui")
                return true;
        }
        return false;
    }

    private static string FormatConstant(TypedConstant tc)
    {
        if (tc.IsNull) return "default!";
        var v = tc.Value;
        return v switch
        {
            bool b => b ? "true" : "false",
            string s => "\"" + s.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"",
            char c => "'" + c + "'",
            float f => f.ToString(System.Globalization.CultureInfo.InvariantCulture) + "f",
            double d => d.ToString(System.Globalization.CultureInfo.InvariantCulture) + "d",
            decimal m => m.ToString(System.Globalization.CultureInfo.InvariantCulture) + "m",
            null => "default!",
            _ => System.Convert.ToString(v, System.Globalization.CultureInfo.InvariantCulture) ?? "default!",
        };
    }

    private static string FormatAccessibility(Accessibility a, Accessibility containerDefault)
    {
        return a switch
        {
            Accessibility.Public => "public",
            Accessibility.Internal => "internal",
            Accessibility.Protected => "protected",
            Accessibility.ProtectedAndInternal => "private protected",
            Accessibility.ProtectedOrInternal => "protected internal",
            Accessibility.Private => "private",
            _ => "",
        };
    }
}

internal sealed record PropertyModel(
    (string Namespace, string TypeName) ContainingTypeKey,
    string Namespace,
    string TypeName,
    string TypeDeclarationKeyword,
    string TypeAccessibility,
    string PropertyName,
    string PropertyTypeDisplay,
    string PropertyAccessibility,
    string GetAccessibility,
    string SetAccessibility,
    bool HasAttributeInitial,
    string? AttributeInitialLiteral,
    bool HasDefaultMethod,
    string DefaultMethodName,
    bool IsValid,
    ImmutableArray<Diagnostic> Diagnostics);
